FROM node:22-slim AS builder

WORKDIR /workspace

COPY package*.json ./
COPY nx.json ./
COPY tsconfig*.json ./
COPY jest.config.ts ./
COPY jest.preset.js ./
COPY .eslint* ./
COPY webpack.*.config.js ./

COPY apps/jobs ./apps/jobs
COPY libs/graphql ./libs/graphql
COPY libs/pulsar ./libs/pulsar
COPY libs/grpc ./libs/grpc
COPY libs/shared ./libs/shared
COPY libs/prisma ./libs/prisma

RUN npm install
RUN apt-get update && apt-get install -y protobuf-compiler
RUN npx nx build jobs

FROM node:22-slim AS runner
WORKDIR /app

COPY --from=builder /workspace/package.json ./

COPY --from=builder /workspace/apps/jobs/package.json ./apps/jobs/package.json

COPY --from=builder /workspace/libs/graphql/package.json ./libs/graphql/package.json
COPY --from=builder /workspace/libs/pulsar/package.json ./libs/pulsar/package.json
COPY --from=builder /workspace/libs/grpc/package.json ./libs/grpc/package.json
COPY --from=builder /workspace/libs/shared/package.json ./libs/shared/package.json
COPY --from=builder /workspace/libs/prisma/package.json ./libs/prisma/package.json
COPY --from=builder /workspace/package-lock.json ./

ENV NODE_ENV=production

RUN npm ci

COPY --from=builder /workspace/dist ./dist

CMD ["node", "dist/apps/jobs/main.js"]